### ISSUE TITLE
jaltol-main error while loading QGIS

### ISSUE THREAD

**Issue by balakumaran247** [atreebangalore/jaltol#3]
**Describe the bug**
jaltol-main throws an error "No module named 'ee'" on loading QGIS

**To Reproduce**
1) Installed GEE plugin
2) Installed Jaltol plugin
3) authenticated the GEE key inside Jaltol
4) used Jaltol functionalities
5) quit QGIS
6) Start QGIS - error pops up

**Expected behavior**
QGIS to load jaltol (successful import of ee module)

**Screenshots**

![Screenshot 2022-02-23 at 9 58 49 AM](https://user-images.githubusercontent.com/77524312/155269316-fb10a000-104c-4a17-991b-7880922d116f.jpg)

After loading QGIS, tried to import 'ee' module in QGIS python console, no errors.
![Screenshot 2022-02-23 at 10 09 42 AM](https://user-images.githubusercontent.com/77524312/155269360-9d20f36a-87d1-47c1-a056-15a55c6733fb.jpg)

**Desktop (please complete the following information):**
 - OS Name and Version : macos 12.2.1
 - QGIS Version: 3.16

**Additional context**
After QGIS loads, while Google Earth Engine plugin had loaded, Jaltol was not available, but it remains activated in the manage plugins tool, reinstalling the Jaltol Plugin does not work, so I uninstalled and installed it again, the Jaltol plugin is installed and activated (didn't ask for GEE authentication) until QGIS quits. so now every time I load QGIS I had to uninstall and install again to access Jaltol.

**Comment by sak-18** [comment]
Any traction on this? Facing a similar issue where I can't load the plugin because of the error displayed.
PS: Actually in my case, the plugin fails to load because of this error. First time haven't downloaded GEE plugin, but later reinstalled the GEE plugin and facing this error.


```
Couldn't load plugin 'jaltol-main' 

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\jaltol-main\__init__.py", line 1, in 
    from .jaltol import JaltolClass
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\jaltol-main\jaltol.py", line 35, in 
    from .jaltol_dialog import JaltolDockWidget
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\jaltol-main\jaltol_dialog.py", line 8, in 
    WIDGET,BASE = uic.loadUiType(os.path.join(
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 540, in 
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1251, in 
    qInitResources()
  File "C:\Users/saketh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\resources.py", line 1242, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct,
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.9-Białowieża Białowieża, a8e9e6fa 

```

**Comment by balakumaran247** [comment]
@sak-18 it seems qgis2web plugin is interfering with Jaltol, so temporary solution would be to disable or uninstall qgis2web plugin.
