### ISSUE TITLE
 Image.load: Image asset 'users/cseicomms/groundwater/sy_mean_cgwb' not found.

### ISSUE THREAD

**Issue by balakumaran247** [atreebangalore/jaltol#6]
**Describe the bug**
Groundwater Change layer cannot be accessed / added to QGIS

**To Reproduce**
1. After selecting a Area of Interest
2. Select a year in Groundwater change dropdown menu
3. Click add
4. Error pops up

**Expected behavior**
Add Groundwater change layer for the specified year to be added to the QGIS workspace

**Screenshots**
![image](https://user-images.githubusercontent.com/77524312/168775401-faafe9d0-2e1b-45a5-bc29-c6d15bd44722.png)

**Desktop (please complete the following information):**
 - OS Name and Version : Windows 11
 - QGIS Version:  3.22.6

**Additional context**

An error has occurred while executing Python code: 

ee.ee_exception.EEException: Image.load: Image asset 'users/cseicomms/groundwater/sy_mean_cgwb' not found. 
Traceback (most recent call last):
  File "C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 338, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\googleapiclient\http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\jaltol-main\jaltol.py", line 392, in add_gw_image
    Map.addLayer(self.gw,gwViz,gw_label,True)
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\Map.py", line 24, in addLayer
    add_or_update_ee_layer(eeObject, visParams, name, shown, opacity)
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 144, in add_or_update_ee_layer
    layer = add_or_update_ee_image_layer(image, name, shown, opacity)
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 157, in add_or_update_ee_image_layer
    layer = add_ee_image_layer(image, name, shown, opacity)
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 47, in add_ee_image_layer
    url = "type=xyz&url=" + get_ee_image_url(image)
  File "C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\utils.py", line 19, in get_ee_image_url
    map_id = ee.data.getMapId({'image': image})
  File "C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 588, in getMapId
    result = _execute_cloud_call(_cloud_api_resource.projects().maps().create(
  File "C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\data.py", line 340, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Image.load: Image asset 'users/cseicomms/groundwater/sy_mean_cgwb' not found.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.6-Białowieża Białowieża, b6f33b1a 

Python Path:
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python
C:/Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.6/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.6\bin\python39.zip
C:\PROGRA~1\QGIS32~1.6\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib
C:\Program Files\QGIS 3.22.6\bin
C:\PROGRA~1\QGIS32~1.6\apps\Python39
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\GDAL-3.4.2-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/atree/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\jaltol-main

**Comment by balakumaran247** [comment]
This was a permission issue on GEE Asset and resolved.
